version: '3'

services:
  ### APP ###
  mc-server-control-discord-bot:
    build: .
    container_name: mc-server-control-discord-bot
    restart: always
    environment:
      - GCP_CREDS_JSON_BASE64=${GCP_CREDS_JSON_BASE64}
      - PROJECT_ID=t-diagram-381919
      - INSTANCE_ZONE=southamerica-east1-b
      - INSTANCE_NAME=minecraft-server
      - DC_BOT_TOKEN=${DC_BOT_TOKEN}
      - DC_CHANNEL_ID=1005923849684123678
      - MC_SERVER_IP=${GCP_MC_SV_IP}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
